import type { Metadata } from "next";
import { Josefin_Sans, Lato } from "next/font/google";
import "./globals.css";
import HeaderBar from "./components/headerBar";
import Navbar from "./components/Navbar";
import Footer from "./components/footer";

// Import fonts using next/font/google

const josefinSans = Josefin_Sans({ subsets: ["latin"], weight: ["300", "400", "600"] });
const lato = Lato({ subsets: ["latin"], weight: ["300", "400", "700"] });

export const metadata: Metadata = {
  title: "Hekto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${josefinSans.className} ${lato.className}`}>
        <HeaderBar />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
